# Generated by Django 3.2.18 on 2023-06-26 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CadastralPlot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cadastral_number', models.CharField(max_length=25, verbose_name='Кадастровый номер')),
                ('short_cadastral_number', models.CharField(blank=True, max_length=20, null=True, verbose_name='Короткий кадастровый номер')),
                ('geometry', models.TextField(verbose_name='Геометрия участка')),
                ('address', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
